python3 run_ibis_tests.py --env_name ${ENV_NAME} --env_check True --save_env True --python_version 3.7 -task benchmark        \
                          --ci_requirements "${PWD}/ci_requirements.yml"                                                      \
                          --ibis_path "${PWD}/../ibis/"                                                                       \
                          -executable "${PWD}/../omniscidb/build/bin/omnisci_server"                                          \
                          -database_name ${DATABASE_NAME} -table census -bench_name census -dfiles_num 1 -iterations 5        \
                          -ipc_conn True -columnar_output True -lazy_fetch False -multifrag_rs True                           \
                          -fragments_size 1000000                                                                             \
                          -data_file '/localdisk/benchmark_datasets/census/ipums_education2income_1970-2010.csv.gz'           \
                          -import_mode fsi -pandas_mode Pandas -ray_tmpdir "/tmp" -optimizer stock                            \
                          -commit_omnisci ${BUILD_REVISION} -commit_ibis ${BUILD_IBIS_REVISION}                               \
                          -commit_omniscripts ${BUILD_OMNISCRIPTS_REVISION}                                                   \
                          -db_server ${DATABASE_SERVER_NAME} -db_port 3306                                                    \
                          -db_user ${DATABASE_USER_NAME} -db-pass "${DATABASE_USER_PW}"                                       \
                          -db_name "${DATABASE_NAME}" -db_table_etl census_etl -db_table_ml census_ml
