# You need libmamba solver for installation or mamba directly due to long modin installation
# https://modin.readthedocs.io/en/stable/getting_started/installation.html
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - scikit-learn-intelex==2023.1.1
  - kaggle
  - boto3
  - modin-all
  - polars==0.18.10
  - git>=2.0.0
  - pip:
    - xgboost>=1.3,<2.0
